var Success = {
  "serviceCode": "AB12",   
  "webTitleNumber":"Test12",
  "agencyOrderId":"Test12",
  "correlationId":"Test12",
  "agencyPortalId":"Test12",
  "properties":"",
  "orgId":"12",
  "parties": [{"role":"owner", "type":"owner", "id":"12","orderId":"12", "firstName":"test", "lastName":"test"}],
  "tgOrder": {
     "customerName": "Surety Title Company",
     "customerOrderId": "ANG-4520",
     "transProcessingNote": "Steven Knight",
     "duedate": "2022-08-11T16:24:55-04:00",
     "stateId": 31,
     "propertyCounty": "MONMOUTH",
     "propertyMunicipality": "Borough of Belmar",
     "propertyAddress": "1008 Fourteenth Ave",
     "parcelId": "139",
     "propertyBlock": "139",
     "propertyLot": "17",
     "orderType": "County Search",
     "searchLength": "60",
     "loanAmount": null,
     "contractPrice": null
   },
   "transaction": {
     "orgId": 2744,
     "agencyName": "Angel Title & Abstract, Inc.",
     "countyCode": null,
     "agencyOrderId": "ANG-4520",
     "note": "Steven Knight",
     "transactionDateTime": "2022-08-09T16:25:12-04:00",
     "agencyShortName": "angelta",
     "state": "NJ",
     "county": "MONMOUTH",
     "municipalityName": "Borough of Belmar",
     "address": "1008 Fourteenth Ave",
     "parcelId": "139",
     "block": "139",
     "lot": "17",
     "searchType": "County Search",
     "property_typeId": "1",
     "policy_typeId": "1",
     "propertyType": "Single Family (1-4)",
     "_txTypeName": "Residential Refinance",
     "searchLength": "60",
     "lender": null,
     "loanAmount": null,
     "comments": "Steven Knight",
     "purchasePrice": null
   },
   "legalDescription": {},
   "vestingDeed": {},
   "_ownerBuyerRows": null,
   "smOrderId": "",
   "smServiceId": "",
   "errors": [],
   "relationshipKey": false
 }
   
   module.exports = {
    Success
  };
  